name: Test
on: push

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'maven'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Format and lint
        run: pnpm check 

      - name: Test
        run: pnpm test 